---
- name: Executing the handlers
  hosts: all
  tasks:
    - name: On the way execute handlers
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: Check the url connection
    - name: Changing the content
      copy:
        content: "Mohan"
        dest: /var/www/html/index.html
      notify: Restart the service    
  handlers:
    - name: Restart the service
      service:
        name: apache2
        state: restarted
    - name: Changing the content
      uri:
        url: "{{item.a}}"       
        status_code: 200
      with_items:
        - http://172.31.82.237
        - http://172.31.86.49    
...
