---
- name: Installing s/w's using when conditon
  hosts: all
  tasks:
    - name: Using when condition
      apt: 
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution== "Ubuntu"

   - name: Installing Git using yum
     yum:
       name: git
       state: present
       update_cache: yes 
     when: ansible_distribution== "CentOS"
...
